# Minecraft Version
minecraft_version=26.2
# Fabric Loader Version
loader_version=0.19.5
# Fabric Loom Version
loom_version=1.18-SNAPSHOT
# Fabric API Version
fabric_version=0.161.0+26.2

# Mod Properties
mod_version=1.1.0
maven_group=com.findtheblock
archives_base_name=findtheblock

# Java Version
java_version=25
