# Minecraft Version
minecraft_version=26.1.2
# Fabric Loader Version
loader_version=0.19.3
# Fabric Loom Version
loom_version=1.17.19
# Fabric API Version
fabric_version=0.155.2+26.1.2

# Mod Properties
mod_version=1.0.0
maven_group=com.findtheblock
archives_base_name=findtheblock

# Java Version
java_version=25
